avoid conflicting updates of the `status.state` of the extension resource by the replication controller
gardener/gardener-extension-shoot-dns-service pull request #56
Opened 2021-05-26 14:29 UTC by MartinWeindel

in parallel

**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
The shoot-dns-service can loose its leader election if there is a high workload because of conflicting updates on replicating changed DNS entries into the DNS state of the extension object.
The replication controller, responsible for replication the entries into the `status.state` of the extension resource, now locks the namespace to avoid conflicting updates. If the namespace is already locked, the reconciliation is delay for about 1-2s.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
avoid conflicting updates of the `status.state` of the extension resource by the replication controller
```

2021-05-28 06:42 UTC, timuthy requested changes
I left one comment in the review and I'm also missing unit tests for `StringLock`. Can you add them?

2021-05-28 06:42 UTC, timuthy commented on pkg/controller/replication/stringslock.go
> +	lock  sync.Mutex
Can you explain the use case you need this particular lock if you already have a look in `StringsLock` that exclusively grants access to `strings`?

2021-05-28 10:23 UTC, MartinWeindel commented
unit test for stringslock has been added

2021-05-31 08:32 UTC, timuthy commented on pkg/controller/replication/stringslock.go
> +	lock  sync.Mutex
As discussed in person, we can replace the `stringMutex` struct and use `lock.TryLock()` instead.

2021-06-01 10:09 UTC, mandelsoft requested changes
Switch to InjectAPIReader in Environment (Env)

2021-06-01 15:37 UTC, mandelsoft approved these changes

2021-06-02 06:14 UTC, timuthy approved these changes
/lgtm

2021-06-02 06:17 UTC, merged